# Generated by Django 5.1.4 on 2024-12-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_alter_document_docfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='advisor',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='author',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='country',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='major',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='year',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
