# Generated by Django 5.1.4 on 2024-12-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_document_advisor_document_author_document_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='themes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
